baseURL: "https://defjm.github.io/hemb/"
languageCode: en-us
title: HEMB
paginate: 10
theme: PaperMod

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Posts
          url: posts
          weight: 10
        - name: Search
          url: search
          weight: 20 
        - name: Tags
          url: tags
          weight: 30 
        - name: Archive
          url: archives
          weight: 40
        - name: About
          url: about
          weight: 50
        - name: Imprint
          url: imprint
          weight: 60

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Hard Eggs & Many Baskets"
  author: DefJM
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  # images: ["images/papermod-cover.png"]

  profileMode:
    enabled: true
    title: Hard Eggs & Many Baskets
    imageUrl: "images/3032471_basket_easter_eggs_plate_icon.png"
    imageTitle: egg
    imageWidth: 200 
    imageHeight: 200
    buttons:
      - name: Posts
        url: posts
        weight: 10
      - name: Search
        url: search
        weight: 20
      - name: Tags
        url: tags
        weight: 30
      - name: Archives
        url: archives
        weight: 40

  homeInfoParams:
    Title: "Hard Eggs & Many Baskets"
    Content: >
      👋 Welcome!

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/defjm/hemb"

  editPost:
    URL: "https://github.com/defjm/hemb/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    favicon: "/assets/favicon.ico"
  
  fuseOpts:
      isCaseSensitive: false
      includeScore: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

